### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Mregy1** [SabatinoMasala/faceless-laravel-example#4]
Hi,
IS there a way to contact you for support? I can't find a contact us page on your website.
If I wanted to remove a series I created. Want to try something else, how can I delete it. It gives me an error when trying to do so.

**Comment by SabatinoMasala** [comment]
That's by design to prevent abuse. Paid plans can create multiple series.

**Comment by Mregy1** [comment]
I created one video and in few minutes another one was created by the system itself without any touch from me.
I was going to try another style to find what suits me before subscribing.

**Comment by Mregy1** [comment]
Also, next post is said to be on 21/03/2025 not next week as advertised.
Another thing, the video duration is 1min and 6 seconds. It won't fit a Youtube short
